"""edited employee department_id relation

Revision ID: 143c5bd6d947
Revises: 9a1e7ba10a27
Create Date: 2026-05-13 14:51:58.577235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143c5bd6d947'
down_revision: Union[str, Sequence[str], None] = '9a1e7ba10a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_department_id_fkey'), 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(op.f('employee_department_id_fkey'), 'employee', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###
